field.formatter.settings.swiper_gallery:
  type: mapping
  label: 'Swiper gallery'
  mapping:
    launcher_main_text:
      type: text
      label: 'Launcher main text'
    show_preview_headline:
      type: boolean
      label: 'Show preview headline'
    preview_type:
      type: text
      label: 'Preview type'
    launcher_thumbnails_text:
      type: text
      label: 'Launcher thumbnails text'
    media_image_field:
      type: text
      label: 'Media image field'
    image_style_gallery_thumbnail:
      type: text
      label: 'Image style gallery thumbnail'
    view_mode_gallery_slide:
      type: text
      label: 'Image viewmode gallery slide'
    view_mode_gallery_preview:
      type: text
      label: 'Image viewmode gallery preview'
    view_mode_gallery_preview_with_thumbs:
      type: text
      label: 'Image viewmode gallery preview with thumbnails'
    view_mode_gallery_preview_thumb:
      type: text
      label: 'Image viewmode preview thumbnails'
    hash_nav_replace_state:
      type: boolean
      label: 'Hash Navigation: replace url state'
    breaker_block:
      type: string
      label: 'Breaker block id'
    breaker_position:
      type: string
      label: 'Breaker position'
