field.formatter.settings.swiper_gallery:
  type: mapping
  label: 'Swiper gallery'
  mapping:
    launcher_main_text:
      type: text
      label: 'Launcher main text'
    show_preview_headline:
      type: boolean
      label: 'Show preview headline'
    preview_footer:
      type: text
      label: 'Preview footer'
    launcher_footer_text:
      type: text
      label: 'Launcher footer text'
    image_style_preview_image:
      type: text
      label: 'Image style preview'
    image_style_preview_thumbnail:
      type: text
      label: 'Image style preview thumbnail'
    image_style_gallery_slide:
      type: text
      label: 'Image style gallery slide'
    image_style_gallery_thumbnail:
      type: text
      label: 'Image style gallery thumbnail'
